### ISSUE TITLE
#TK17 Logueo front

### ISSUE THREAD

**Issue by fedekrenn** [ISPC-23/FullStack2023#17]
Creación de formulario de logueo e implementación de feedback según datos correctos o incorrectos
Historia de usuario #US08

**Comment by Ferbarletta** [comment]
Se crea el formulario de logueo.
Queda pendiente:
a.- Ordenar en diseño
b.- Implementar el feedback
c.- Revisar validaciones.

**Comment by Ferbarletta** [comment]
a.- Ordenar en diseño: Se le dio estilo a la page.
b.- Implementar el feedback: Pendiente
c.- Revisar validaciones: Valida tipo de campo email y contraseña.

**Comment by Ferbarletta** [comment]
Se abre la tarjeta, se agrega validación de 3 intentos de logueo y en el caso de usuario y contraseña correcta se redirecciona a la page index.html. Finamente se cierra nuevamente esta tarjeta.
