### ISSUE TITLE
#TK32 Estructura de carpetas

### ISSUE THREAD

**Issue by fedekrenn** [ISPC-23/FullStack2023#32]
Actualización de nombres de carpetas y archivos para seguir una estructura en común

**Comment by fedekrenn** [comment]
- [x] Eliminar carpeta documentación
- [x] Eliminar modelo físico
- [x] Renombrar capeta "Base de datos" por "database"

**Comment by Ferbarletta** [comment]
En la carpeta database quedan los archivos bdtienda.sql y relational_model.mwb.
