### ISSUE TITLE
#TK38 Añadir icono sesion

### ISSUE THREAD

**Issue by fedekrenn** [ISPC-23/FullStack2023#38]
Añadir en el header el icono que navegará a la page de registro/logueo
Historia de usuario #US07 y #US08

**Comment by Ferbarletta** [comment]
Se agrega el botón "Iniciar sesión" que linkea al la página login.
Queda pendiente acomodarlo sobre el margen derecho del la barra de navegación

**Comment by fedekrenn** [comment]
Se verifica ticket realizado por @Ferbarletta
