### ISSUE TITLE
#TK49 Modificación clase

### ISSUE THREAD

**Issue by fedekrenn** [ISPC-23/FullStack2023#49]
Modificación de la estructura de clases

- [x] Aplicar las recomendaciones de atributos que indica el profesor
- [x] Crear la clase que corresponde al producto en la DB

**Comment by fedekrenn** [comment]
Se modifica las clases de models con las correcciones realizadas por la profesora, además se cambian algunos nombres para que coincida con la base de datos (por ejemplo nro_compra se reemplaza por id_compra)

**Comment by fedekrenn** [comment]
Debido a que realizamos varios cambios en la db, actualizamos las clase modelo en python para que repliquen la info

**Comment by FernandaACastillo** [comment]
Se añade los métodos a las clases de acceso DAO
